Solicitud de julianbesso1 para la legion
Striderx90/legion-del-mal pull request #1
Opened 2020-09-02 23:32 UTC by julianbesso1

### Modificaciones
Agregué a Scarecrow

2020-09-02 23:43 UTC, Striderx90 requested changes
Por favor, no borren al espantapajaros

2020-09-02 23:43 UTC, Striderx90 commented on miembros.md
> +23. Scarecrow
No quiero que agreguen a Scarecrow

2020-09-02 23:46 UTC, julianbesso1 commented on miembros.md
> +23. Scarecrow
Puedo poner a otro villano?

2020-09-03 00:03 UTC, Striderx90 submitted a review, later dismissed
Aprobado!

2020-09-03 00:07 UTC, Striderx90 reviewed
Random Comment

2020-09-03 00:08 UTC, julianbesso1 commented
Random Response

2020-09-03 00:09 UTC, Striderx90 commented
asdfasdfasdf

2020-09-03 00:11 UTC, Striderx90 approved these changes

2020-09-03 00:30 UTC, merged